<meta charset="UTF-8">
<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
<p>Vážená paní / Vážený pane,</p>

<p>informujeme Vás, že v systému <a href="${appUrl}">Indihu Mind</a> Vám bylo zmeněno heslo.</p>
<p>Datum změny:
<p><b>${datetime}</b></p>

<p>Pokud jste tuto akci neprovedl/a, informujte svého administrátora.</p>


<hr>
<p>Systém Indihu Mind</p>
<p style="color: #666666">Tento e-mail byl vygenerován automaticky, prosím, neodpovídejte na něj.</p>