env: deploy # deploy / staging (for test data initialization)

spring:
  application:
    name: Indihu Mind
  freemarker:
    checkTemplateLocation: false
  datasource:
    url: jdbc:postgresql://localhost:5432/vzb
    username: uas
    password: vuji61oilo
    driver-class-name: org.postgresql.Driver
    name: mainPool
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50250KB # 50MB + 10KB buffer for request fields
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail: # data for connecting to SMTP server
    host: INSERT_VALUE_HERE
    port: 0 # INSERT_VALUE_HERE
    username: INSERT_VALUE_HERE
    password: INSERT_VALUE_HERE
    protocol: INSERT_VALUE_HERE
    properties.mail.smtp:
      auth: true
      starttls.enable: false
      ssl.trust: INSERT_VALUE_HERE
      ssl.enable: true
  liquibase:
    changeLog: classpath:/dbchangelog.vzb.xml
    url: jdbc:postgresql://localhost:5432/vzb
    user: INSERT_VALUE_HERE
    password: INSERT_VALUE_HERE

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    max-http-form-post-size: -1
    max-swallow-size: -1

mail: # data for creating email in UAS MailCenter
  sender:
    email: noreply@mind.indihu.cz
    name: Indihu Mind
  app:
    name: Indihu Mind
    logo: logo.png
    url: https://mind.indihu.cz
  enabled: true

security:
  basic:
    authQuery: "/api/login"
  jwt:
    secret: INSERT_VALUE_HERE # Secret encoded in Base64 format
    expiration: 300000 # Seconds
    refresh: 30 # Seconds
  password:
    length: 8
    digit: true
    alphabet: true

logging:
  file.path: ../logs

file.path: filerepository

json:
  serializeNulls: true

vzb:
  index:
    endpoint: http://localhost:8983/solr
  token:
    expirationTime: 15 # Minutes
  quota:
    kbPerUser: 10000000 # 10GB
  marc:
    template:
      placeholder: ${?}
      missing-data: (%s%s NENALEZENO)
    pdf-name: citace # without extension .pdf
  attachment:
    local:
      file:
        path: local-attachment-files
  report:
    card: 6764540c-826c-4c24-a850-e7827d28bd60
    cards-csv: eba436f6-93cb-44f8-aa08-b6452799be8f