spring.application.name: vzb
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vzb
    username: uas
    password: vuji61oilo
    driver-class-name: org.postgresql.Driver
    name: mainPool
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10250KB # 10MB + 10KB buffer for request fields
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 465
    username: noreply@inqool.cz
    password: blah38espro
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: false
      ssl.trust: smtp.gmail.com
      ssl.enable: true
  liquibase:
    changeLog: classpath:/dbchangelog.vzb.xml
    url: jdbc:postgresql://localhost:5432/vzb
    user: uas
    password: vuji61oilo
mail:
  sender:
    email: noreply@indihumind.inqool.cz
    name: Indihu Mind
  app:
    name: Indihu Mind
    logo: logo.png
    link: http://indihumind.inqool.cz
    url: http://indihumind.inqool.cz
  enabled: true
security:
  basic:
    authQuery: "/api/login"
  jwt:
    secret: YXVyYTI0Z3JvZ3M=
    expiration: 300000
    refresh: 30
  password:
    length: 8
    digit: true
    alphabet: true
file.path: filerepository
json:
  serializeNulls: true
env: deploy # staging / deploy
vzb:
  index:
    endpoint: http://localhost:8983/solr
    cardCollectionName: card
  token:
    expirationTime: 15 # Minutes
  quota:
    kbPerUser: 10000000
  marc:
    template:
      placeholder: ${?}
    pdf-name: citace # without extension .pdf
server:
  url: http://localhost:8080