package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.card.CardContent;
import cz.cas.lib.vzb.card.attribute.Attribute;
import cz.cas.lib.vzb.card.attribute.AttributeType;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class AttributeBuilder {
    private final Attribute attribute;

    private AttributeBuilder() {
        attribute = new Attribute();
    }

    public static AttributeBuilder builder() {
        return new AttributeBuilder();
    }

    public AttributeBuilder cardContent(CardContent cardContent) {
        attribute.setCardContent(cardContent);
        return this;
    }

    public AttributeBuilder ordinalNumber(int ordinalNumber) {
        attribute.setOrdinalNumber(ordinalNumber);
        return this;
    }

    public AttributeBuilder name(String name) {
        attribute.setName(name);
        return this;
    }

    public AttributeBuilder type(AttributeType type) {
        attribute.setType(type);
        return this;
    }

    public AttributeBuilder value(Object value) {
        attribute.setValue(value);
        return this;
    }

    public AttributeBuilder jsonValue(String jsonValue) {
        attribute.setJsonValue(jsonValue);
        return this;
    }

    public AttributeBuilder id(String id) {
        attribute.setId(id);
        return this;
    }

    public Attribute build() {
        return attribute;
    }

}
