package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.card.Card;
import cz.cas.lib.vzb.card.CardContent;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class CardContentBuilder {
    private final CardContent cardContent;

    private CardContentBuilder() {
        cardContent = new CardContent();
    }

    public static CardContentBuilder builder() {
        return new CardContentBuilder();
    }

    public CardContentBuilder origin(CardContent origin) {
        cardContent.setOrigin(origin);
        return this;
    }

    public CardContentBuilder lastVersion(boolean lastVersion) {
        cardContent.setLastVersion(lastVersion);
        return this;
    }

    public CardContentBuilder card(Card card) {
        cardContent.setCard(card);
        return this;
    }

    public CardContentBuilder id(String id) {
        cardContent.setId(id);
        return this;
    }

    public CardContent build() {
        return cardContent;
    }

}
