package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.card.label.Label;
import cz.cas.lib.vzb.security.user.User;

import java.awt.*;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class LabelBuilder {
    private final Label label;

    private LabelBuilder() {
        label = new Label();
    }

    public static LabelBuilder builder() {
        return new LabelBuilder();
    }

    public LabelBuilder name(String name) {
        label.setName(name);
        return this;
    }

    public LabelBuilder color(Color color) {
        label.setColor(color);
        return this;
    }

    public LabelBuilder owner(User owner) {
        label.setOwner(owner);
        return this;
    }

    public LabelBuilder id(String id) {
        label.setId(id);
        return this;
    }

    public Label build() {
        return label;
    }

}
