package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.attachment.LocalAttachmentFile;
import cz.cas.lib.vzb.card.Card;
import cz.cas.lib.vzb.reference.marc.record.Citation;
import cz.cas.lib.vzb.security.user.User;

import java.io.InputStream;

import static core.util.Utils.asSet;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class LocalAttachmentBuilder {
    private final LocalAttachmentFile localAttachmentFile;

    private LocalAttachmentBuilder() {
        localAttachmentFile = new LocalAttachmentFile();
    }

    public static LocalAttachmentBuilder builder() {
        return new LocalAttachmentBuilder();
    }

    public LocalAttachmentBuilder contentType(String contentType) {
        localAttachmentFile.setContentType(contentType);
        return this;
    }

    public LocalAttachmentBuilder stream(InputStream stream) {
        localAttachmentFile.setStream(stream);
        return this;
    }

    public LocalAttachmentBuilder size(Long size) {
        localAttachmentFile.setSize(size);
        return this;
    }

    public LocalAttachmentBuilder owner(User owner) {
        localAttachmentFile.setOwner(owner);
        return this;
    }

    public LocalAttachmentBuilder type(String type) {
        localAttachmentFile.setType(type);
        return this;
    }

    public LocalAttachmentBuilder cards(Card... linkedCards) {
        localAttachmentFile.setLinkedCards(asSet(linkedCards));
        return this;
    }

    public LocalAttachmentBuilder records(Citation... records) {
        localAttachmentFile.setRecords(asSet(records));
        return this;
    }

    public LocalAttachmentBuilder name(String name) {
        localAttachmentFile.setName(name);
        return this;
    }

    public LocalAttachmentBuilder id(String id) {
        localAttachmentFile.setId(id);
        return this;
    }

    public LocalAttachmentFile build() {
        return localAttachmentFile;
    }
}
