package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.attachment.UrlAttachmentFile;
import cz.cas.lib.vzb.card.Card;
import cz.cas.lib.vzb.reference.marc.record.Citation;
import cz.cas.lib.vzb.security.user.User;

import java.io.InputStream;

import static core.util.Utils.asSet;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class UrlAttachmentBuilder {
    private final UrlAttachmentFile urlAttachmentFile;

    private UrlAttachmentBuilder() {
        urlAttachmentFile = new UrlAttachmentFile();
    }

    public static UrlAttachmentBuilder builder() {
        return new UrlAttachmentBuilder();
    }

    public UrlAttachmentBuilder link(String link) {
        urlAttachmentFile.setLink(link);
        return this;
    }

    public UrlAttachmentBuilder contentType(String contentType) {
        urlAttachmentFile.setContentType(contentType);
        return this;
    }

    public UrlAttachmentBuilder stream(InputStream stream) {
        urlAttachmentFile.setStream(stream);
        return this;
    }

    public UrlAttachmentBuilder size(Long size) {
        urlAttachmentFile.setSize(size);
        return this;
    }

    public UrlAttachmentBuilder owner(User owner) {
        urlAttachmentFile.setOwner(owner);
        return this;
    }

    public UrlAttachmentBuilder type(String type) {
        urlAttachmentFile.setType(type);
        return this;
    }

    public UrlAttachmentBuilder cards(Card... linkedCards) {
        urlAttachmentFile.setLinkedCards(asSet(linkedCards));
        return this;
    }

    public UrlAttachmentBuilder records(Citation... records) {
        urlAttachmentFile.setRecords(asSet(records));
        return this;
    }

    public UrlAttachmentBuilder name(String name) {
        urlAttachmentFile.setName(name);
        return this;
    }

    public UrlAttachmentBuilder id(String id) {
        urlAttachmentFile.setId(id);
        return this;
    }

    public UrlAttachmentFile build() {
        return urlAttachmentFile;
    }
}
