package cz.cas.lib.vzb.init.builders;

import cz.cas.lib.vzb.security.user.User;

/**
 * Generated by Builder Generator plugin.
 * Can be re-generated manually if changes to attributes occur.
 */
public final class UserBuilder {
    private final User user;

    private UserBuilder() {
        user = new User();
    }

    public static UserBuilder builder() {
        return new UserBuilder();
    }

    public UserBuilder password(String password) {
        user.setPassword(password);
        return this;
    }

    public UserBuilder email(String email) {
        user.setEmail(email);
        return this;
    }

    public UserBuilder allowed(boolean allowed) {
        user.setAllowed(allowed);
        return this;
    }

    public UserBuilder id(String id) {
        user.setId(id);
        return this;
    }

    public User build() {
        return user;
    }

}
