version: "3.3"

volumes:
  data:

services:
  postgres:
    container_name: postgres
    image: "postgres:12.3"
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    environment: # properties from application.yml
      - "POSTGRES_USER=uas"
      - "POSTGRES_PASSWORD=vuji61oilo"
      - "POSTGRES_DB=vzb"

  # TODO: Solr needs tweaks for uas core. Contents of managed schema must be sent to docker (mby via API?)
  solr:
    container_name: solr
    image: "solr:8.4.1"
    restart: always
    ports:
      - "8985:8983" # Solr Admin UI for docker is available at http://localhost:8985/solr
    volumes: # link folder from host computer with docker folder
      - ./src/main/resources/index/:/opt/solr/conf/
    command: 'bash -e -c "precreate-core card; precreate-core uas;

              cp /opt/solr/conf/schema.xml /var/solr/data/card/conf/schema.xml; 
              cp /opt/solr/conf/solrconfig.xml /var/solr/data/card/conf/solrconfig.xml; 
              rm /var/solr/data/card/conf/managed-schema; 

              solr-foreground;"'

  app:
    container_name: indihu
    build:
      context: ./
      dockerfile: local-docker # dockerfile for local development
    environment: # override properties of application.yml
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vzb"
      - "SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/vzb"
      - "VZB_INDEX_ENDPOINT=http://solr:8983/solr"
      - "SPRING_PROFILE=docker"
    restart: always
    ports:
      - "8080:8080" # Swagger available at http://localhost:8080/swagger-ui.html#
